export interface ExerciseGuide {
  exerciseId: string;
  title: string;
  imageSrc: string;
  imageAlt: string;
  muscleImageSrc: string;
  muscleImageAlt: string;
  setup: string[];
  movement: string[];
  mistakes: string[];
  selfChecks: string[];
  tempo: string;
  breathing: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  safetyNote: string;
}

const guides: ExerciseGuide[] = [
  {
    exerciseId: 'barbell-bench',
    title: 'Barbell bench press',
    imageSrc: '/exercises/barbell-bench-guide.webp',
    imageAlt: 'Barbell bench press shown at the top and controlled bottom positions.',
    muscleImageSrc: '/exercises/barbell-bench-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a flat barbell bench press showing the chest in green and the triceps and front shoulders in amber.',
    setup: ['Plant both feet and keep your hips in contact with the bench.', 'Pull your shoulder blades back and down before unracking.', 'Grip so your forearms are vertical at the bottom.'],
    movement: ['Lower the bar under control toward the lower chest.', 'Keep wrists stacked over elbows and elbows below the shoulders.', 'Press up and slightly back without bouncing the bar.'],
    mistakes: ['Flaring the elbows straight out', 'Lifting the hips to finish a repetition', 'Losing shoulder position or bouncing the bar'],
    selfChecks: ['From the side, the bar finishes over the shoulder and touches near the lower chest.', 'From the foot end, both wrists remain stacked above the elbows.', 'The first and final repetition use the same controlled touch point and hip position.'],
    tempo: 'Lower for about 2 seconds, pause softly at the chest, then press with control.',
    breathing: 'Brace before the descent; exhale through the press without losing your rib or shoulder position.',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'front deltoids'],
    safetyNote: 'Use safeties or a spotter when benching with a barbell. Stop if you feel sharp shoulder, elbow, or chest pain.',
  },
  {
    exerciseId: 'box-squat',
    title: 'Controlled box squat',
    imageSrc: '/exercises/box-squat-guide.webp',
    imageAlt: 'Barbell box squat shown standing and at a controlled touch to the box.',
    muscleImageSrc: '/exercises/box-squat-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a box squat showing the quadriceps and glutes in green with supporting hamstrings, inner thighs, back, and core in amber.',
    setup: ['Set the box at a pain-free depth and the rack safeties just below it.', 'Brace before unracking and use a stable stance.', 'Keep pressure balanced through the whole foot.'],
    movement: ['Send hips back while allowing the knees to track over the toes.', 'Touch the box under control without relaxing your torso.', 'Drive through the floor and stand tall without rocking forward.'],
    mistakes: ['Collapsing the knees inward', 'Dropping quickly or fully sitting back', 'Rounding the lower back or shifting onto the toes'],
    selfChecks: ['From the front, each knee follows the direction of the middle toes throughout the repetition.', 'From the side, the bar stays above the mid-foot and the torso angle remains controlled.', 'The box touch is quiet and repeatable rather than a drop or backward rock.'],
    tempo: 'Descend for 2–3 seconds, touch the box without relaxing, then stand smoothly.',
    breathing: 'Take a brace before descending; maintain pressure through the touch and exhale as you pass the hardest point.',
    primaryMuscles: ['Quadriceps', 'glutes'],
    secondaryMuscles: ['Hamstrings', 'core'],
    safetyNote: 'Use a load and depth you can control. Stop if back, hip, or knee discomfort becomes sharp or changes your movement.',
  },
  {
    exerciseId: 'standing-calf-raise',
    title: 'Supported standing calf raise',
    imageSrc: '/exercises/standing-calf-raise-guide.webp',
    imageAlt: 'Supported single-leg standing calf raise shown with the working heel lowered below a stable block and raised under control.',
    muscleImageSrc: '/exercises/standing-calf-raise-muscles.webp',
    muscleImageAlt: 'Rear-side anatomical illustrations of a standing calf raise showing the working gastrocnemius and soleus in green with supporting foot and ankle stabilizers in amber.',
    setup: ['Place the ball of one foot securely on a low stable block beside the rack.', 'Use one hand lightly on the rack for balance and hold optional load in the opposite hand.', 'Tuck the free foot behind, keep hips level, and leave the working knee softly unlocked.'],
    movement: ['Lower the working heel slowly only as far as the ankle remains aligned and controlled.', 'Press through the ball of the foot and rise tall without rolling onto the outer or inner edge.', 'Pause briefly at the top, then begin the next slow descent without bouncing.'],
    mistakes: ['Bouncing out of the bottom or rushing the lowering phase', 'Allowing the ankle to roll inward or outward', 'Leaning heavily into the rack or locking the working knee aggressively'],
    selfChecks: ['From behind, the heel travels vertically rather than drifting inward or outward.', 'From the side, the torso stays upright and the rise comes from the ankle rather than a hip movement.', 'Both the lowered and raised positions are quiet, balanced, and repeatable.'],
    tempo: 'Lower for about 3 seconds, rise for 1–2 seconds, and pause briefly at the top.',
    breathing: 'Breathe normally and exhale during the rise without losing balance or trunk position.',
    primaryMuscles: ['Gastrocnemius', 'soleus'],
    secondaryMuscles: ['Foot stabilizers', 'ankle stabilizers', 'core', 'hip stabilizers'],
    safetyNote: 'Use a non-slip stable block and rack support. Start without added load and stop for sharp foot, ankle, calf, knee, or balance-related discomfort.',
  },
  {
    exerciseId: 'dead-bugs',
    title: 'Dead bug',
    imageSrc: '/exercises/dead-bug-guide.webp',
    imageAlt: 'Dead bug shown in the starting position and with opposite arm and leg extended.',
    muscleImageSrc: '/exercises/dead-bug-muscles.webp',
    muscleImageAlt: 'Elevated side anatomical illustrations of a dead bug showing the abdominal wall in green with supporting hip flexors and trunk stabilizers in amber.',
    setup: ['Lie on your back with hips and knees at 90 degrees.', 'Reach your arms toward the ceiling and gently brace your abdomen.', 'Exhale enough to bring your ribs down toward the mat.'],
    movement: ['Slowly extend one leg and the opposite arm.', 'Move only as far as you can without your lower back lifting.', 'Return with control, reset your brace, and switch sides.'],
    mistakes: ['Arching the lower back', 'Moving quickly instead of controlling the range', 'Holding your breath or extending too far'],
    selfChecks: ['Place fingertips under the lower back and keep the pressure steady as the limbs move.', 'From the side, the ribs stay down rather than lifting as the arm reaches overhead.', 'Both sides use the same pain-free range and controlled speed.'],
    tempo: 'Reach for about 3 seconds, pause briefly, and return for about 2 seconds.',
    breathing: 'Exhale during the reach to maintain the brace; inhale quietly as you return and reset.',
    primaryMuscles: ['Deep core'],
    secondaryMuscles: ['Hip flexors'],
    safetyNote: 'Shorten the range if your lower back lifts from the mat. Stop if the movement causes back pain.',
  },
  {
    exerciseId: 'dumbbell-overhead-press',
    title: 'Dumbbell overhead press',
    imageSrc: '/exercises/dumbbell-overhead-press-guide-v2.webp',
    imageAlt: 'Dumbbell overhead press shown with weights at shoulder level and controlled overhead lockout.',
    muscleImageSrc: '/exercises/dumbbell-overhead-press-muscles.webp',
    muscleImageAlt: 'Front anatomical illustrations of a dumbbell overhead press showing the deltoids in green and supporting triceps, upper chest, and core in amber.',
    setup: ['Sit or stand tall with feet stable and ribs stacked over the pelvis.', 'Start with wrists above elbows and dumbbells just outside the shoulders.', 'Brace before pressing and keep your head neutral.'],
    movement: ['Press the dumbbells upward without leaning back.', 'Allow the arms to travel naturally while keeping the forearms near vertical.', 'Finish with the weights over the shoulders, then lower under control.'],
    mistakes: ['Arching the lower back to move the weight', 'Letting wrists fold backward or elbows drift far behind the torso', 'Crashing the dumbbells together or dropping the descent'],
    selfChecks: ['From the side, the weights finish above the shoulders rather than in front of the face.', 'From the front, wrists remain stacked above elbows through the lower half.', 'Your rib position and torso angle look the same on the first and last repetition.'],
    tempo: 'Press smoothly for about 1–2 seconds and lower for about 2 seconds.',
    breathing: 'Brace before pressing; exhale through the effort while keeping the ribs stacked, then inhale as you reset.',
    primaryMuscles: ['Deltoids'],
    secondaryMuscles: ['Triceps', 'upper chest'],
    safetyNote: 'Use a load you can press without leaning back. Stop if you feel sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'chest-supported-row',
    title: 'Chest-supported dumbbell row',
    imageSrc: '/exercises/chest-supported-row-guide-v2.webp',
    imageAlt: 'Chest-supported dumbbell row shown with arms extended and elbows pulled beside the torso.',
    muscleImageSrc: '/exercises/chest-supported-row-muscles.webp',
    muscleImageAlt: 'Rear three-quarter anatomical illustrations of a chest-supported row showing the lats and middle back in green with supporting rear shoulders and arms in amber.',
    setup: ['Set the bench angle so your chest is supported without forcing your neck upward.', 'Plant your feet and let the dumbbells hang with shoulders controlled.', 'Keep the ribs against the pad and wrists neutral.'],
    movement: ['Pull the elbows beside the torso while the chest stays on the pad.', 'Pause briefly when the shoulder blades move back without shrugging.', 'Lower until the arms are long while maintaining shoulder control.'],
    mistakes: ['Lifting the chest from the pad to finish the pull', 'Shrugging the shoulders toward the ears', 'Swinging the dumbbells or shortening the controlled reach'],
    selfChecks: ['From the side, the chest remains in contact with the pad throughout each repetition.', 'From behind, the shoulders stay level and the elbows follow similar paths.', 'The bottom position shows long arms without the shoulders suddenly rolling forward.'],
    tempo: 'Pull for about 1 second, pause briefly, and lower for 2–3 seconds.',
    breathing: 'Exhale as you pull; inhale during the controlled reach without losing contact with the pad.',
    primaryMuscles: ['Upper back', 'lats'],
    secondaryMuscles: ['Biceps', 'rear deltoids'],
    safetyNote: 'Adjust the bench and load if you cannot keep your torso supported. Stop for sharp shoulder, neck, or back pain.',
  },
  {
    exerciseId: 'hip-thrust',
    title: 'Barbell hip thrust',
    imageSrc: '/exercises/hip-thrust-guide-v2.webp',
    imageAlt: 'Hip thrust shown in the lowered position and at a controlled shoulder-to-knee lockout.',
    muscleImageSrc: '/exercises/hip-thrust-muscles.webp',
    muscleImageAlt: 'Rear-side anatomical illustrations of a barbell hip thrust showing the glutes in green and supporting hamstrings, quadriceps, and core in amber.',
    setup: ['Place the lower shoulder blades against a stable bench and pad the bar across the hip crease.', 'Set feet so the shins are near vertical at the top.', 'Keep the chin gently tucked and ribs controlled.'],
    movement: ['Lower the hips under control while the upper back stays supported.', 'Drive through the whole foot and lift the hips without throwing the head back.', 'Finish when shoulders, hips, and knees form a controlled line, then pause.'],
    mistakes: ['Overextending the lower back above the natural lockout', 'Pushing through the toes or letting knees collapse inward', 'Using momentum or allowing the bench to move'],
    selfChecks: ['From the side, the top position forms a line from shoulders through hips to knees.', 'At lockout, the shins are close to vertical and pressure remains through the whole foot.', 'The ribs remain down and the finish comes from the hips rather than a lower-back arch.'],
    tempo: 'Lift for about 1–2 seconds, pause at lockout, and lower for about 2 seconds.',
    breathing: 'Brace before lifting; exhale near lockout while keeping the ribs down, then inhale as you lower.',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings', 'quadriceps'],
    safetyNote: 'Use a stable bench, secure plates, and adequate bar padding. Stop for sharp back, hip, or knee pain.',
  },
  {
    exerciseId: 'push-up',
    title: 'Push-up',
    imageSrc: '/exercises/push-up-guide.webp',
    imageAlt: 'Standard floor push-up shown in a high plank and at a controlled bottom position with a straight head-to-heel body line.',
    muscleImageSrc: '/exercises/push-up-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a push-up showing the chest and triceps in green with the front shoulders, serratus, and abdominal wall in amber.',
    setup: ['Place hands slightly wider than shoulder width with fingers pointing forward.', 'Extend into a high plank with the head, ribs, pelvis, and heels forming one controlled line.', 'Set the shoulders away from the ears and brace before the first descent.'],
    movement: ['Lower the chest between the hands while the elbows travel about 30–45 degrees from the torso.', 'Stop at the deepest position where the body line and shoulder control remain unchanged.', 'Press the floor away and return to a long-arm plank without letting the hips lead or lag.'],
    mistakes: ['Flaring the elbows straight out from the shoulders', 'Letting the hips sag, pike upward, or move before the chest', 'Dropping quickly or forcing depth after the body line changes'],
    selfChecks: ['From the side, the ears, shoulders, hips, knees, and ankles remain in one line.', 'From the front, both elbows track at similar angles and the chest lowers between the hands.', 'The torso reaches and leaves the bottom position as one unit without the lower back sagging.'],
    tempo: 'Lower for about 3 seconds, pause softly, and press up in 1–2 seconds.',
    breathing: 'Inhale during the controlled descent; exhale through the press while keeping the trunk braced.',
    primaryMuscles: ['Chest', 'triceps'],
    secondaryMuscles: ['Front deltoids', 'serratus anterior', 'core'],
    safetyNote: 'Use an elevated stable surface if floor repetitions change your body line. Stop for sharp wrist, elbow, shoulder, chest, or back pain.',
  },
  {
    exerciseId: 'band-face-pull',
    title: 'Band face pull',
    imageSrc: '/exercises/band-face-pull-guide.webp',
    imageAlt: 'Standing resistance-band face pull shown with arms extended toward a face-height rack anchor and the band pulled beside the face with controlled external rotation.',
    muscleImageSrc: '/exercises/band-face-pull-muscles.webp',
    muscleImageAlt: 'Rear anatomical illustrations of a band face pull showing the rear shoulders, rhomboids, and middle trapezius in green with supporting rotator cuff, arms, and core in amber.',
    setup: ['Secure the band to a stable rack around upper-chest to face height and check the anchor before loading it.', 'Take a staggered stance with light band tension, soft knees, and ribs stacked over the pelvis.', 'Hold one end in each hand with arms long, wrists neutral, and shoulders relaxed away from the ears.'],
    movement: ['Pull the band ends toward either side of the face while the elbows travel outward slightly below shoulder height.', 'Rotate the forearms toward vertical and bring the shoulder blades back without forcing them together.', 'Return slowly until the arms are long while keeping the torso and neck still.'],
    mistakes: ['Shrugging the shoulders or lifting the elbows far above shoulder height', 'Leaning backward or arching the lower back to finish the pull', 'Snapping the band forward or letting the wrists fold'],
    selfChecks: ['From the side, the head, ribs, and hips remain stacked rather than drifting backward.', 'From behind, both elbows and hands finish at similar heights without one shoulder shrugging.', 'At the finish, the band ends sit beside the face and the forearms angle toward vertical.'],
    tempo: 'Pull for about 2 seconds, pause briefly, and return for about 3 seconds.',
    breathing: 'Exhale through the pull; inhale during the slow return while keeping the ribs stacked.',
    primaryMuscles: ['Rear deltoids', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['Rotator cuff', 'biceps', 'forearms', 'core'],
    safetyNote: 'Inspect the band and anchor before every set. Use controlled tension and stop for sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'lateral-raise',
    title: 'Dumbbell lateral raise',
    imageSrc: '/exercises/dumbbell-lateral-raise-guide.webp',
    imageAlt: 'Standing dumbbell lateral raise shown with the weights beside the thighs and raised under control to shoulder height.',
    muscleImageSrc: '/exercises/dumbbell-lateral-raise-muscles.webp',
    muscleImageAlt: 'Front anatomical illustrations of a dumbbell lateral raise showing the middle deltoids in green with supporting shoulder and upper-trapezius muscles in amber.',
    setup: ['Stand tall with feet about hip-width apart, knees soft, and ribs stacked over the pelvis.', 'Hold light dumbbells beside the thighs with neutral wrists and relaxed shoulders.', 'Set the arms slightly forward of the exact side plane and keep a soft bend in the elbows.'],
    movement: ['Lead with the elbows and raise both arms smoothly without swinging the torso.', 'Stop around shoulder height or earlier if that is your comfortable controlled range.', 'Lower the dumbbells slowly until the shoulders reset without letting the weights drop.'],
    mistakes: ['Shrugging the shoulders toward the ears', 'Swinging the dumbbells or leaning to create momentum', 'Raising above a comfortable shoulder-height endpoint or bending the wrists'],
    selfChecks: ['From the front, both elbows travel evenly and remain softly bent.', 'From the side, the arms stay slightly forward of the torso rather than drifting behind it.', 'Your head, ribs, and hips remain in the same position from the first repetition to the last.'],
    tempo: 'Raise for about 2 seconds, pause briefly, and lower for about 3 seconds.',
    breathing: 'Exhale during the controlled raise; inhale as you lower without losing your stacked posture.',
    primaryMuscles: ['Middle deltoids'],
    secondaryMuscles: ['Front deltoids', 'supraspinatus', 'upper trapezius'],
    safetyNote: 'Use a light load and a comfortable range you can control without shrugging. Stop for sharp shoulder, neck, or elbow pain.',
  },
  {
    exerciseId: 'barbell-rdl',
    title: 'Barbell Romanian deadlift',
    imageSrc: '/exercises/barbell-rdl-guide-v2.webp',
    imageAlt: 'Barbell Romanian deadlift shown standing tall and hinged with the bar near mid-shin at a controlled endpoint.',
    muscleImageSrc: '/exercises/barbell-rdl-muscles-v2.webp',
    muscleImageAlt: 'Rear anatomical illustrations of a barbell Romanian deadlift showing the glutes and distinct posterior hamstring muscles in green, with supporting back, core, and forearm muscles in amber.',
    setup: ['Stand with the bar close to the upper thighs and feet about hip-width apart.', 'Soften the knees, brace the trunk, and keep the shoulders controlled.', 'Use a double-overhand grip just outside the legs.'],
    movement: ['Push the hips backward while keeping the bar close to the legs.', 'Lower toward mid-shin only while the spine stays neutral and hamstring tension remains controlled.', 'Drive the floor away and bring the hips forward to stand tall without leaning back.'],
    mistakes: ['Turning the hinge into a deep squat', 'Letting the bar drift away from the legs', 'Rounding the back or forcing extra depth'],
    selfChecks: ['From the side, the hips travel backward while the knees keep a soft bend and the shins stay nearly vertical.', 'The bar remains above the mid-foot and close to the thighs and shins.', 'Mid-shin is a reference, not a required depth; stop when hamstring range or spinal position would otherwise change.'],
    tempo: 'Lower for about 3 seconds, pause briefly at your controlled depth, then stand in 1–2 seconds.',
    breathing: 'Brace before hinging; keep pressure through the descent and exhale as you return to standing.',
    primaryMuscles: ['Hamstrings', 'glutes'],
    secondaryMuscles: ['Spinal erectors', 'lats', 'upper back', 'forearms', 'core'],
    safetyNote: 'Use safeties and a load you can keep close to the body. Stop for sharp back, hip, or hamstring pain.',
  },
];

export function exerciseGuide(exerciseId: string): ExerciseGuide | undefined {
  return guides.find((guide) => guide.exerciseId === exerciseId);
}

export function exerciseGuideIds(): string[] {
  return guides.map((guide) => guide.exerciseId);
}

export function exerciseGuides(): ExerciseGuide[] {
  return guides.map((guide) => ({
    ...guide,
    setup: [...guide.setup],
    movement: [...guide.movement],
    mistakes: [...guide.mistakes],
    selfChecks: [...guide.selfChecks],
    primaryMuscles: [...guide.primaryMuscles],
    secondaryMuscles: [...guide.secondaryMuscles],
  }));
}
