export interface ExerciseGuide {
  exerciseId: string;
  title: string;
  imageSrc: string;
  imageAlt: string;
  muscleImageSrc: string;
  muscleImageAlt: string;
  setup: string[];
  movement: string[];
  mistakes: string[];
  selfChecks: string[];
  tempo: string;
  breathing: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  safetyNote: string;
}

const guides: ExerciseGuide[] = [
  {
    exerciseId: 'barbell-bench',
    title: 'Barbell bench press',
    imageSrc: '/exercises/barbell-bench-guide.webp',
    imageAlt: 'Barbell bench press shown at the top and controlled bottom positions.',
    muscleImageSrc: '/exercises/barbell-bench-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a flat barbell bench press showing the chest in green and the triceps and front shoulders in amber.',
    setup: ['Plant both feet and keep your hips in contact with the bench.', 'Pull your shoulder blades back and down before unracking.', 'Grip so your forearms are vertical at the bottom.'],
    movement: ['Lower the bar under control toward the lower chest.', 'Keep wrists stacked over elbows and elbows below the shoulders.', 'Press up and slightly back without bouncing the bar.'],
    mistakes: ['Flaring the elbows straight out', 'Lifting the hips to finish a repetition', 'Losing shoulder position or bouncing the bar'],
    selfChecks: ['From the side, the bar finishes over the shoulder and touches near the lower chest.', 'From the foot end, both wrists remain stacked above the elbows.', 'The first and final repetition use the same controlled touch point and hip position.'],
    tempo: 'Lower for about 2 seconds, pause softly at the chest, then press with control.',
    breathing: 'Brace before the descent; exhale through the press without losing your rib or shoulder position.',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'front deltoids'],
    safetyNote: 'Use safeties or a spotter when benching with a barbell. Stop if you feel sharp shoulder, elbow, or chest pain.',
  },
  {
    exerciseId: 'box-squat',
    title: 'Controlled box squat',
    imageSrc: '/exercises/box-squat-guide.webp',
    imageAlt: 'Barbell box squat shown standing and at a controlled touch to the box.',
    muscleImageSrc: '/exercises/box-squat-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a box squat showing the quadriceps and glutes in green with supporting hamstrings, inner thighs, back, and core in amber.',
    setup: ['Set the box at a pain-free depth and the rack safeties just below it.', 'Brace before unracking and use a stable stance.', 'Keep pressure balanced through the whole foot.'],
    movement: ['Send hips back while allowing the knees to track over the toes.', 'Touch the box under control without relaxing your torso.', 'Drive through the floor and stand tall without rocking forward.'],
    mistakes: ['Collapsing the knees inward', 'Dropping quickly or fully sitting back', 'Rounding the lower back or shifting onto the toes'],
    selfChecks: ['From the front, each knee follows the direction of the middle toes throughout the repetition.', 'From the side, the bar stays above the mid-foot and the torso angle remains controlled.', 'The box touch is quiet and repeatable rather than a drop or backward rock.'],
    tempo: 'Descend for 2–3 seconds, touch the box without relaxing, then stand smoothly.',
    breathing: 'Take a brace before descending; maintain pressure through the touch and exhale as you pass the hardest point.',
    primaryMuscles: ['Quadriceps', 'glutes'],
    secondaryMuscles: ['Hamstrings', 'core'],
    safetyNote: 'Use a load and depth you can control. Stop if back, hip, or knee discomfort becomes sharp or changes your movement.',
  },
  {
    exerciseId: 'bodyweight-squat',
    title: 'Bodyweight squat',
    imageSrc: '/exercises/bodyweight-squat-guide.webp',
    imageAlt: 'Bodyweight squat shown standing with arms forward and at a controlled comfortable depth with both feet planted.',
    muscleImageSrc: '/exercises/bodyweight-squat-muscles.webp',
    muscleImageAlt: 'Rear three-quarter sports anatomy illustrations of a bodyweight squat showing the quadriceps and glutes in green with supporting hamstrings, adductors, calves, back, and core in amber.',
    setup: ['Stand with feet around shoulder-width apart and toes turned out only as needed for comfort.', 'Balance pressure across the heel, base of the big toe, and base of the little toe.', 'Reach the arms forward, stack the ribs over the pelvis, and brace gently before moving.'],
    movement: ['Sit the hips down and slightly back while allowing both knees to follow the toes.', 'Descend only as far as both feet stay planted and the torso remains controlled.', 'Press the floor away and stand tall without snapping the knees or leaning backward.'],
    mistakes: ['Letting the knees collapse inward or the feet roll onto their edges', 'Lifting the heels or forcing a depth that changes spinal or pelvic position', 'Dropping quickly, shifting strongly to one side, or using momentum to stand'],
    selfChecks: ['From the front, both knees track in the direction of the middle toes and the hips remain centered.', 'From the side, the whole foot stays planted and the torso angle changes smoothly rather than collapsing.', 'The first and final repetitions reach the same controlled, pain-free depth without balance corrections.'],
    tempo: 'Lower for about 3 seconds, pause softly at your controlled depth, and stand in 1–2 seconds.',
    breathing: 'Inhale and brace before descending; exhale as you press the floor away and return to standing.',
    primaryMuscles: ['Quadriceps', 'glutes'],
    secondaryMuscles: ['Hamstrings', 'adductors', 'calves', 'core'],
    safetyNote: 'Use a stable support or reduce depth if balance changes. Stop for sharp knee, hip, ankle, or back pain.',
  },
  {
    exerciseId: 'standing-calf-raise',
    title: 'Supported standing calf raise',
    imageSrc: '/exercises/standing-calf-raise-guide.webp',
    imageAlt: 'Supported single-leg standing calf raise shown with the working heel lowered below a stable block and raised under control.',
    muscleImageSrc: '/exercises/standing-calf-raise-muscles.webp',
    muscleImageAlt: 'Rear-side anatomical illustrations of a standing calf raise showing the working gastrocnemius and soleus in green with supporting foot and ankle stabilizers in amber.',
    setup: ['Place the ball of one foot securely on a low stable block beside the rack.', 'Use one hand lightly on the rack for balance and hold optional load in the opposite hand.', 'Tuck the free foot behind, keep hips level, and leave the working knee softly unlocked.'],
    movement: ['Lower the working heel slowly only as far as the ankle remains aligned and controlled.', 'Press through the ball of the foot and rise tall without rolling onto the outer or inner edge.', 'Pause briefly at the top, then begin the next slow descent without bouncing.'],
    mistakes: ['Bouncing out of the bottom or rushing the lowering phase', 'Allowing the ankle to roll inward or outward', 'Leaning heavily into the rack or locking the working knee aggressively'],
    selfChecks: ['From behind, the heel travels vertically rather than drifting inward or outward.', 'From the side, the torso stays upright and the rise comes from the ankle rather than a hip movement.', 'Both the lowered and raised positions are quiet, balanced, and repeatable.'],
    tempo: 'Lower for about 3 seconds, rise for 1–2 seconds, and pause briefly at the top.',
    breathing: 'Breathe normally and exhale during the rise without losing balance or trunk position.',
    primaryMuscles: ['Gastrocnemius', 'soleus'],
    secondaryMuscles: ['Foot stabilizers', 'ankle stabilizers', 'core', 'hip stabilizers'],
    safetyNote: 'Use a non-slip stable block and rack support. Start without added load and stop for sharp foot, ankle, calf, knee, or balance-related discomfort.',
  },
  {
    exerciseId: 'split-squat',
    title: 'Dumbbell split squat',
    imageSrc: '/exercises/dumbbell-split-squat-guide.webp',
    imageAlt: 'Dumbbell split squat shown in a tall staggered stance and at a controlled bottom position with the rear knee close to the floor.',
    muscleImageSrc: '/exercises/dumbbell-split-squat-muscles.webp',
    muscleImageAlt: 'Rear three-quarter anatomical illustrations of a dumbbell split squat showing the lead-leg glutes and quadriceps in green with supporting hamstrings, adductors, calves, and core in amber.',
    setup: ['Stand with feet on two parallel tracks rather than a tightrope, with the rear heel raised.', 'Hold one dumbbell in each hand and distribute enough weight through the lead foot to keep it planted.', 'Set a stance length that lets both knees bend while the torso remains tall and controlled.'],
    movement: ['Lower straight down by bending both knees while the lead knee follows the direction of the toes.', 'Stop before balance, heel pressure, or pelvic position changes; the rear knee may approach the floor but does not need to touch.', 'Drive through the whole lead foot to return to the tall split stance without stepping between repetitions.'],
    mistakes: ['Using a tightrope stance that makes balance unreliable', 'Letting the lead knee collapse inward or the lead heel lift', 'Pushing mostly from the rear foot, bouncing at the bottom, or stepping forward like a walking lunge'],
    selfChecks: ['From the front, the feet remain on separate tracks and the lead knee follows the middle toes.', 'From the side, the lead foot stays planted and the torso angle remains consistent through the descent.', 'The start and finish use the same foot positions, with no step needed between repetitions.'],
    tempo: 'Lower for about 3 seconds, pause softly at your controlled depth, then stand in 1–2 seconds.',
    breathing: 'Brace before descending; inhale through the controlled lowering phase and exhale as you drive back to standing.',
    primaryMuscles: ['Quadriceps', 'glutes'],
    secondaryMuscles: ['Hamstrings', 'adductors', 'calves', 'core'],
    safetyNote: 'Begin with bodyweight or light dumbbells near a stable support. Stop for sharp knee, hip, ankle, or back pain, or if balance cannot be maintained.',
  },
  {
    exerciseId: 'reverse-lunge',
    title: 'Bodyweight reverse lunge',
    imageSrc: '/exercises/reverse-lunge-guide.webp',
    imageAlt: 'Bodyweight reverse lunge shown from a tall feet-together start and after one leg steps backward into a controlled bottom position.',
    muscleImageSrc: '/exercises/reverse-lunge-muscles.webp',
    muscleImageAlt: 'Rear three-quarter sports anatomy illustrations of a reverse lunge showing the stationary lead-leg glutes and quadriceps in green with supporting hamstrings, adductors, calves, and core in amber.',
    setup: ['Stand tall with feet about hip-width apart and enough clear space behind you.', 'Keep the pelvis level, ribs stacked, and hands at the hips or near a stable support.', 'Choose the leg that will stay planted and establish balanced pressure across that whole foot.'],
    movement: ['Step the other foot backward and land softly on the ball of that foot.', 'Lower both knees under control while the stationary lead knee follows the direction of the toes.', 'Drive through the whole lead foot and bring the rear foot forward to the original stance without rushing the balance transition.'],
    mistakes: ['Stepping backward on a tightrope or too short to lower with control', 'Letting the lead knee collapse inward or the lead heel lift', 'Pushing mostly from the rear foot, slamming the rear knee down, or turning the repetition into a forward lunge'],
    selfChecks: ['From the front, the stepping foot lands on its own track and the lead knee follows the middle toes.', 'From the side, the lead foot remains planted while the rear heel stays raised in the bottom position.', 'Each repetition finishes in the same tall stance without an extra hop or balance correction.'],
    tempo: 'Step back smoothly, lower for about 3 seconds, pause softly, then return to standing in 1–2 seconds.',
    breathing: 'Brace before stepping; inhale during the controlled descent and exhale as you drive back to the start.',
    primaryMuscles: ['Quadriceps', 'glutes'],
    secondaryMuscles: ['Hamstrings', 'adductors', 'calves', 'core'],
    safetyNote: 'Start beside a stable support and shorten the step or depth if balance changes. Stop for sharp knee, hip, ankle, or back pain.',
  },
  {
    exerciseId: 'dead-bugs',
    title: 'Dead bug',
    imageSrc: '/exercises/dead-bug-guide.webp',
    imageAlt: 'Dead bug shown in the starting position and with opposite arm and leg extended.',
    muscleImageSrc: '/exercises/dead-bug-muscles.webp',
    muscleImageAlt: 'Elevated side anatomical illustrations of a dead bug showing the abdominal wall in green with supporting hip flexors and trunk stabilizers in amber.',
    setup: ['Lie on your back with hips and knees at 90 degrees.', 'Reach your arms toward the ceiling and gently brace your abdomen.', 'Exhale enough to bring your ribs down toward the mat.'],
    movement: ['Slowly extend one leg and the opposite arm.', 'Move only as far as you can without your lower back lifting.', 'Return with control, reset your brace, and switch sides.'],
    mistakes: ['Arching the lower back', 'Moving quickly instead of controlling the range', 'Holding your breath or extending too far'],
    selfChecks: ['Place fingertips under the lower back and keep the pressure steady as the limbs move.', 'From the side, the ribs stay down rather than lifting as the arm reaches overhead.', 'Both sides use the same pain-free range and controlled speed.'],
    tempo: 'Reach for about 3 seconds, pause briefly, and return for about 2 seconds.',
    breathing: 'Exhale during the reach to maintain the brace; inhale quietly as you return and reset.',
    primaryMuscles: ['Deep core'],
    secondaryMuscles: ['Hip flexors'],
    safetyNote: 'Shorten the range if your lower back lifts from the mat. Stop if the movement causes back pain.',
  },
  {
    exerciseId: 'dumbbell-overhead-press',
    title: 'Dumbbell overhead press',
    imageSrc: '/exercises/dumbbell-overhead-press-guide-v2.webp',
    imageAlt: 'Dumbbell overhead press shown with weights at shoulder level and controlled overhead lockout.',
    muscleImageSrc: '/exercises/dumbbell-overhead-press-muscles.webp',
    muscleImageAlt: 'Front anatomical illustrations of a dumbbell overhead press showing the deltoids in green and supporting triceps, upper chest, and core in amber.',
    setup: ['Sit or stand tall with feet stable and ribs stacked over the pelvis.', 'Start with wrists above elbows and dumbbells just outside the shoulders.', 'Brace before pressing and keep your head neutral.'],
    movement: ['Press the dumbbells upward without leaning back.', 'Allow the arms to travel naturally while keeping the forearms near vertical.', 'Finish with the weights over the shoulders, then lower under control.'],
    mistakes: ['Arching the lower back to move the weight', 'Letting wrists fold backward or elbows drift far behind the torso', 'Crashing the dumbbells together or dropping the descent'],
    selfChecks: ['From the side, the weights finish above the shoulders rather than in front of the face.', 'From the front, wrists remain stacked above elbows through the lower half.', 'Your rib position and torso angle look the same on the first and last repetition.'],
    tempo: 'Press smoothly for about 1–2 seconds and lower for about 2 seconds.',
    breathing: 'Brace before pressing; exhale through the effort while keeping the ribs stacked, then inhale as you reset.',
    primaryMuscles: ['Deltoids'],
    secondaryMuscles: ['Triceps', 'upper chest'],
    safetyNote: 'Use a load you can press without leaning back. Stop if you feel sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'chest-supported-row',
    title: 'Chest-supported dumbbell row',
    imageSrc: '/exercises/chest-supported-row-guide-v2.webp',
    imageAlt: 'Chest-supported dumbbell row shown with arms extended and elbows pulled beside the torso.',
    muscleImageSrc: '/exercises/chest-supported-row-muscles.webp',
    muscleImageAlt: 'Rear three-quarter anatomical illustrations of a chest-supported row showing the lats and middle back in green with supporting rear shoulders and arms in amber.',
    setup: ['Set the bench angle so your chest is supported without forcing your neck upward.', 'Plant your feet and let the dumbbells hang with shoulders controlled.', 'Keep the ribs against the pad and wrists neutral.'],
    movement: ['Pull the elbows beside the torso while the chest stays on the pad.', 'Pause briefly when the shoulder blades move back without shrugging.', 'Lower until the arms are long while maintaining shoulder control.'],
    mistakes: ['Lifting the chest from the pad to finish the pull', 'Shrugging the shoulders toward the ears', 'Swinging the dumbbells or shortening the controlled reach'],
    selfChecks: ['From the side, the chest remains in contact with the pad throughout each repetition.', 'From behind, the shoulders stay level and the elbows follow similar paths.', 'The bottom position shows long arms without the shoulders suddenly rolling forward.'],
    tempo: 'Pull for about 1 second, pause briefly, and lower for 2–3 seconds.',
    breathing: 'Exhale as you pull; inhale during the controlled reach without losing contact with the pad.',
    primaryMuscles: ['Upper back', 'lats'],
    secondaryMuscles: ['Biceps', 'rear deltoids'],
    safetyNote: 'Adjust the bench and load if you cannot keep your torso supported. Stop for sharp shoulder, neck, or back pain.',
  },
  {
    exerciseId: 'prone-y-raise',
    title: 'Chest-supported prone Y raise',
    imageSrc: '/exercises/prone-y-raise-guide.webp',
    imageAlt: 'Chest-supported prone Y raise shown with arms hanging toward the floor and raised diagonally overhead into a controlled Y position.',
    muscleImageSrc: '/exercises/prone-y-raise-muscles.webp',
    muscleImageAlt: 'Rear three-quarter sports anatomy illustrations of a prone Y raise showing the lower trapezius and rear shoulders in green with the middle trapezius, rhomboids, rotator cuff, and trunk stabilizers in amber.',
    setup: ['Set an incline bench low enough to support the chest while both feet remain firmly planted.', 'Lie face-down with the head neutral and arms hanging long toward the floor.', 'Turn the thumbs upward and aim the arms diagonally overhead so they will form a Y rather than a T.'],
    movement: ['Raise both arms diagonally overhead while the chest remains in contact with the pad.', 'Reach long through the thumbs and keep the shoulders away from the ears.', 'Stop at the highest position you can control without shrugging or arching, then lower slowly.'],
    mistakes: ['Lifting the chest or arching the lower back to create range', 'Shrugging toward the ears or turning the movement into a lateral T raise', 'Bending the elbows, swinging the arms, or forcing them above the controlled torso line'],
    selfChecks: ['From behind, both arms form an even Y and rise to a similar height.', 'From the side, the chest remains on the pad and the neck stays aligned with the torso.', 'The shoulder blades move smoothly without the shoulders closing the space beside the ears.'],
    tempo: 'Raise for about 2 seconds, pause briefly in the controlled Y, and lower for about 3 seconds.',
    breathing: 'Exhale during the raise; inhale through the slow return while keeping the ribs supported by the bench.',
    primaryMuscles: ['Lower trapezius', 'rear deltoids'],
    secondaryMuscles: ['Middle trapezius', 'rhomboids', 'rotator cuff', 'core'],
    safetyNote: 'Begin without added weight and use a pain-free range. Stop for sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'hip-thrust',
    title: 'Barbell hip thrust',
    imageSrc: '/exercises/hip-thrust-guide-v2.webp',
    imageAlt: 'Hip thrust shown in the lowered position and at a controlled shoulder-to-knee lockout.',
    muscleImageSrc: '/exercises/hip-thrust-muscles.webp',
    muscleImageAlt: 'Rear-side anatomical illustrations of a barbell hip thrust showing the glutes in green and supporting hamstrings, quadriceps, and core in amber.',
    setup: ['Place the lower shoulder blades against a stable bench and pad the bar across the hip crease.', 'Set feet so the shins are near vertical at the top.', 'Keep the chin gently tucked and ribs controlled.'],
    movement: ['Lower the hips under control while the upper back stays supported.', 'Drive through the whole foot and lift the hips without throwing the head back.', 'Finish when shoulders, hips, and knees form a controlled line, then pause.'],
    mistakes: ['Overextending the lower back above the natural lockout', 'Pushing through the toes or letting knees collapse inward', 'Using momentum or allowing the bench to move'],
    selfChecks: ['From the side, the top position forms a line from shoulders through hips to knees.', 'At lockout, the shins are close to vertical and pressure remains through the whole foot.', 'The ribs remain down and the finish comes from the hips rather than a lower-back arch.'],
    tempo: 'Lift for about 1–2 seconds, pause at lockout, and lower for about 2 seconds.',
    breathing: 'Brace before lifting; exhale near lockout while keeping the ribs down, then inhale as you lower.',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings', 'quadriceps'],
    safetyNote: 'Use a stable bench, secure plates, and adequate bar padding. Stop for sharp back, hip, or knee pain.',
  },
  {
    exerciseId: 'push-up',
    title: 'Push-up',
    imageSrc: '/exercises/push-up-guide.webp',
    imageAlt: 'Standard floor push-up shown in a high plank and at a controlled bottom position with a straight head-to-heel body line.',
    muscleImageSrc: '/exercises/push-up-muscles.webp',
    muscleImageAlt: 'Front three-quarter anatomical illustrations of a push-up showing the chest and triceps in green with the front shoulders, serratus, and abdominal wall in amber.',
    setup: ['Place hands slightly wider than shoulder width with fingers pointing forward.', 'Extend into a high plank with the head, ribs, pelvis, and heels forming one controlled line.', 'Set the shoulders away from the ears and brace before the first descent.'],
    movement: ['Lower the chest between the hands while the elbows travel about 30–45 degrees from the torso.', 'Stop at the deepest position where the body line and shoulder control remain unchanged.', 'Press the floor away and return to a long-arm plank without letting the hips lead or lag.'],
    mistakes: ['Flaring the elbows straight out from the shoulders', 'Letting the hips sag, pike upward, or move before the chest', 'Dropping quickly or forcing depth after the body line changes'],
    selfChecks: ['From the side, the ears, shoulders, hips, knees, and ankles remain in one line.', 'From the front, both elbows track at similar angles and the chest lowers between the hands.', 'The torso reaches and leaves the bottom position as one unit without the lower back sagging.'],
    tempo: 'Lower for about 3 seconds, pause softly, and press up in 1–2 seconds.',
    breathing: 'Inhale during the controlled descent; exhale through the press while keeping the trunk braced.',
    primaryMuscles: ['Chest', 'triceps'],
    secondaryMuscles: ['Front deltoids', 'serratus anterior', 'core'],
    safetyNote: 'Use an elevated stable surface if floor repetitions change your body line. Stop for sharp wrist, elbow, shoulder, chest, or back pain.',
  },
  {
    exerciseId: 'band-face-pull',
    title: 'Band face pull',
    imageSrc: '/exercises/band-face-pull-guide.webp',
    imageAlt: 'Standing resistance-band face pull shown with arms extended toward a face-height rack anchor and the band pulled beside the face with controlled external rotation.',
    muscleImageSrc: '/exercises/band-face-pull-muscles.webp',
    muscleImageAlt: 'Rear anatomical illustrations of a band face pull showing the rear shoulders, rhomboids, and middle trapezius in green with supporting rotator cuff, arms, and core in amber.',
    setup: ['Secure the band to a stable rack around upper-chest to face height and check the anchor before loading it.', 'Take a staggered stance with light band tension, soft knees, and ribs stacked over the pelvis.', 'Hold one end in each hand with arms long, wrists neutral, and shoulders relaxed away from the ears.'],
    movement: ['Pull the band ends toward either side of the face while the elbows travel outward slightly below shoulder height.', 'Rotate the forearms toward vertical and bring the shoulder blades back without forcing them together.', 'Return slowly until the arms are long while keeping the torso and neck still.'],
    mistakes: ['Shrugging the shoulders or lifting the elbows far above shoulder height', 'Leaning backward or arching the lower back to finish the pull', 'Snapping the band forward or letting the wrists fold'],
    selfChecks: ['From the side, the head, ribs, and hips remain stacked rather than drifting backward.', 'From behind, both elbows and hands finish at similar heights without one shoulder shrugging.', 'At the finish, the band ends sit beside the face and the forearms angle toward vertical.'],
    tempo: 'Pull for about 2 seconds, pause briefly, and return for about 3 seconds.',
    breathing: 'Exhale through the pull; inhale during the slow return while keeping the ribs stacked.',
    primaryMuscles: ['Rear deltoids', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['Rotator cuff', 'biceps', 'forearms', 'core'],
    safetyNote: 'Inspect the band and anchor before every set. Use controlled tension and stop for sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'lateral-raise',
    title: 'Dumbbell lateral raise',
    imageSrc: '/exercises/dumbbell-lateral-raise-guide.webp',
    imageAlt: 'Standing dumbbell lateral raise shown with the weights beside the thighs and raised under control to shoulder height.',
    muscleImageSrc: '/exercises/dumbbell-lateral-raise-muscles.webp',
    muscleImageAlt: 'Front anatomical illustrations of a dumbbell lateral raise showing the middle deltoids in green with supporting shoulder and upper-trapezius muscles in amber.',
    setup: ['Stand tall with feet about hip-width apart, knees soft, and ribs stacked over the pelvis.', 'Hold light dumbbells beside the thighs with neutral wrists and relaxed shoulders.', 'Set the arms slightly forward of the exact side plane and keep a soft bend in the elbows.'],
    movement: ['Lead with the elbows and raise both arms smoothly without swinging the torso.', 'Stop around shoulder height or earlier if that is your comfortable controlled range.', 'Lower the dumbbells slowly until the shoulders reset without letting the weights drop.'],
    mistakes: ['Shrugging the shoulders toward the ears', 'Swinging the dumbbells or leaning to create momentum', 'Raising above a comfortable shoulder-height endpoint or bending the wrists'],
    selfChecks: ['From the front, both elbows travel evenly and remain softly bent.', 'From the side, the arms stay slightly forward of the torso rather than drifting behind it.', 'Your head, ribs, and hips remain in the same position from the first repetition to the last.'],
    tempo: 'Raise for about 2 seconds, pause briefly, and lower for about 3 seconds.',
    breathing: 'Exhale during the controlled raise; inhale as you lower without losing your stacked posture.',
    primaryMuscles: ['Middle deltoids'],
    secondaryMuscles: ['Front deltoids', 'supraspinatus', 'upper trapezius'],
    safetyNote: 'Use a light load and a comfortable range you can control without shrugging. Stop for sharp shoulder, neck, or elbow pain.',
  },
  {
    exerciseId: 'barbell-rdl',
    title: 'Barbell Romanian deadlift',
    imageSrc: '/exercises/barbell-rdl-guide-v2.webp',
    imageAlt: 'Barbell Romanian deadlift shown standing tall and hinged with the bar near mid-shin at a controlled endpoint.',
    muscleImageSrc: '/exercises/barbell-rdl-muscles-v2.webp',
    muscleImageAlt: 'Rear anatomical illustrations of a barbell Romanian deadlift showing the glutes and distinct posterior hamstring muscles in green, with supporting back, core, and forearm muscles in amber.',
    setup: ['Stand with the bar close to the upper thighs and feet about hip-width apart.', 'Soften the knees, brace the trunk, and keep the shoulders controlled.', 'Use a double-overhand grip just outside the legs.'],
    movement: ['Push the hips backward while keeping the bar close to the legs.', 'Lower toward mid-shin only while the spine stays neutral and hamstring tension remains controlled.', 'Drive the floor away and bring the hips forward to stand tall without leaning back.'],
    mistakes: ['Turning the hinge into a deep squat', 'Letting the bar drift away from the legs', 'Rounding the back or forcing extra depth'],
    selfChecks: ['From the side, the hips travel backward while the knees keep a soft bend and the shins stay nearly vertical.', 'The bar remains above the mid-foot and close to the thighs and shins.', 'Mid-shin is a reference, not a required depth; stop when hamstring range or spinal position would otherwise change.'],
    tempo: 'Lower for about 3 seconds, pause briefly at your controlled depth, then stand in 1–2 seconds.',
    breathing: 'Brace before hinging; keep pressure through the descent and exhale as you return to standing.',
    primaryMuscles: ['Hamstrings', 'glutes'],
    secondaryMuscles: ['Spinal erectors', 'lats', 'upper back', 'forearms', 'core'],
    safetyNote: 'Use safeties and a load you can keep close to the body. Stop for sharp back, hip, or hamstring pain.',
  },
  {
    exerciseId: 'goblet-squat', title: 'Goblet squat', imageSrc: '/exercises/goblet-squat-guide.webp', imageAlt: 'Goblet squat shown standing with one dumbbell at the chest and at a controlled squat depth.', muscleImageSrc: '/exercises/goblet-squat-muscles.webp', muscleImageAlt: 'Front anatomical goblet squat illustrations showing quadriceps and glutes in green with hamstrings, adductors, calves, and core in amber.',
    setup: ['Hold one dumbbell vertically against the chest.', 'Set feet at a comfortable squat width with whole-foot pressure.', 'Brace with ribs stacked over the pelvis.'], movement: ['Sit down between the hips as the knees track with the toes.', 'Keep the load close and stop at your controlled depth.', 'Press the floor away and stand without leaning back.'], mistakes: ['Letting the heels lift or knees collapse inward', 'Holding the dumbbell away from the chest', 'Forcing depth after the torso or pelvis changes'], selfChecks: ['From the front, knees follow the middle toes.', 'From the side, the dumbbell stays close and feet remain planted.', 'Each repetition reaches the same controlled range.'], tempo: 'Lower for about 3 seconds, pause softly, and stand in 1–2 seconds.', breathing: 'Brace before descending and exhale as you stand.', primaryMuscles: ['Quadriceps', 'glutes'], secondaryMuscles: ['Hamstrings', 'adductors', 'calves', 'core'], safetyNote: 'Start with a light dumbbell and stop for sharp knee, hip, ankle, or back pain.',
  },
  {
    exerciseId: 'dumbbell-hip-thrust', title: 'Dumbbell hip thrust', imageSrc: '/exercises/dumbbell-hip-thrust-guide.webp', imageAlt: 'Dumbbell hip thrust shown with hips lowered and at a controlled shoulder-to-knee lockout.', muscleImageSrc: '/exercises/dumbbell-hip-thrust-muscles.webp', muscleImageAlt: 'Side anatomical dumbbell hip thrust illustrations showing glutes in green with hamstrings, quadriceps, and core in amber.',
    setup: ['Support the lower shoulder blades on a stable bench.', 'Center one padded dumbbell across the hip crease.', 'Plant feet so shins approach vertical at lockout.'], movement: ['Lower the hips while the upper back stays supported.', 'Drive through whole feet and lift without throwing the head back.', 'Stop at a level shoulder-to-knee line and squeeze briefly.'], mistakes: ['Arching the lower back above natural lockout', 'Letting knees collapse or feet slide', 'Using momentum or an unstable bench'], selfChecks: ['From the side, shoulders, hips, and knees align at the top.', 'Both feet remain planted with shins near vertical.', 'The dumbbell stays centered throughout the range.'], tempo: 'Lift for 1–2 seconds, pause, and lower for about 2 seconds.', breathing: 'Brace before lifting and exhale near lockout.', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings', 'quadriceps', 'core'], safetyNote: 'Use a stable bench and padded manageable load; stop for sharp back, hip, or knee pain.',
  },
  {
    exerciseId: 'glute-bridge', title: 'Floor glute bridge', imageSrc: '/exercises/glute-bridge-guide.webp', imageAlt: 'Floor glute bridge shown with hips resting on the mat and at a controlled shoulder-to-knee lockout.', muscleImageSrc: '/exercises/glute-bridge-muscles.webp', muscleImageAlt: 'Side anatomical glute bridge illustrations showing glutes in green with hamstrings, quadriceps, and core in amber.',
    setup: ['Lie on the back with knees bent and feet planted.', 'Place arms beside the body and keep ribs controlled.', 'Set feet where the heels remain comfortable.'], movement: ['Press through whole feet and lift the hips.', 'Finish when shoulders, hips, and knees form a controlled line.', 'Lower slowly until the pelvis returns to the mat.'], mistakes: ['Overarching the lower back', 'Pushing only through the toes', 'Letting knees collapse or bouncing'], selfChecks: ['From the side, the top forms a shoulder-to-knee line.', 'Both feet maintain even pressure.', 'The ribs stay down as the hips finish.'], tempo: 'Lift for 2 seconds, pause briefly, and lower for 2–3 seconds.', breathing: 'Exhale during the lift and inhale during the return.', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings', 'quadriceps', 'core'], safetyNote: 'Reduce range if the back takes over and stop for sharp back, hip, or knee pain.',
  },
  {
    exerciseId: 'band-glute-bridge', title: 'Resistance-band glute bridge', imageSrc: '/exercises/band-glute-bridge-guide.webp', imageAlt: 'Band glute bridge shown with hips on the mat and lifted while a loop band stays above the knees.', muscleImageSrc: '/exercises/band-glute-bridge-muscles.webp', muscleImageAlt: 'Side anatomical band glute bridge illustrations showing gluteus maximus and medius in green with hamstrings, quadriceps, and core in amber.',
    setup: ['Place an intact loop band around the thighs just above the knees.', 'Lie on the back with knees bent and feet planted.', 'Keep gentle outward knee tension and ribs controlled.'], movement: ['Press through whole feet and lift the hips.', 'Maintain knee alignment against the band without forcing them wide.', 'Pause at the shoulder-to-knee line and lower slowly.'], mistakes: ['Letting the knees collapse inward', 'Overarching the back or pushing only through toes', 'Using a band that rolls, tears, or changes foot position'], selfChecks: ['From the front, knees remain aligned over the feet.', 'From the side, shoulders, hips, and knees form a line.', 'Band position stays above both knees.'], tempo: 'Lift for 2 seconds, pause briefly, and lower for 2–3 seconds.', breathing: 'Exhale during the lift and inhale during the return.', primaryMuscles: ['Gluteus maximus', 'gluteus medius'], secondaryMuscles: ['Hamstrings', 'quadriceps', 'core'], safetyNote: 'Use a comfortable intact band and stop for sharp back, hip, or knee pain.',
  },
  {
    exerciseId: 'band-squat', title: 'Resistance-band squat', imageSrc: '/exercises/band-squat-guide.webp', imageAlt: 'Band squat shown standing on the band with its ends at the shoulders and at a controlled squat depth.', muscleImageSrc: '/exercises/band-squat-muscles.webp', muscleImageAlt: 'Front anatomical band squat illustrations showing quadriceps and glutes in green with hamstrings, adductors, calves, and core in amber.',
    setup: ['Stand securely on the center of an intact band.', 'Hold equal band lengths at the shoulders.', 'Set a comfortable stance and brace.'], movement: ['Descend while knees follow the toes and feet stay planted.', 'Keep the band paths clear of the face and neck.', 'Stand smoothly against increasing tension.'], mistakes: ['Using a damaged band or uneven lengths', 'Letting knees collapse or heels lift', 'Snapping into lockout or losing the band underfoot'], selfChecks: ['From the front, band tension and knee paths stay even.', 'From the side, the feet remain planted.', 'The band stays beneath both feet through the full range.'], tempo: 'Lower for about 3 seconds and stand in 1–2 seconds without snapping.', breathing: 'Brace before descending and exhale while standing.', primaryMuscles: ['Quadriceps', 'glutes'], secondaryMuscles: ['Hamstrings', 'adductors', 'calves', 'core'], safetyNote: 'Inspect and secure the band before use; stop for sharp pain or any slipping or tearing.',
  },
  {
    exerciseId: 'dumbbell-floor-press', title: 'Dumbbell floor press', imageSrc: '/exercises/dumbbell-floor-press-guide.webp', imageAlt: 'Dumbbell floor press shown with upper arms softly contacting the floor and weights pressed above the shoulders.', muscleImageSrc: '/exercises/dumbbell-floor-press-muscles.webp', muscleImageAlt: 'Front anatomical floor press illustrations showing chest and triceps in green with front shoulders, serratus, and core in amber.',
    setup: ['Lie on the floor with knees bent and feet planted.', 'Hold dumbbells above the elbows with neutral wrists.', 'Set shoulder blades gently back and down.'], movement: ['Lower until the upper arms touch the floor softly.', 'Pause without relaxing the shoulders.', 'Press the dumbbells above the shoulders without colliding them.'], mistakes: ['Bouncing elbows from the floor', 'Folding wrists or flaring elbows straight out', 'Arching aggressively to shorten the range'], selfChecks: ['From the side, wrists remain over elbows.', 'Both upper arms touch down at the same controlled point.', 'The weights finish above the shoulders.'], tempo: 'Lower for 2–3 seconds, pause softly, and press in 1–2 seconds.', breathing: 'Inhale during the descent and exhale through the press.', primaryMuscles: ['Chest', 'triceps'], secondaryMuscles: ['Front deltoids', 'serratus anterior', 'core'], safetyNote: 'Use weights you can lower safely to the floor and stop for sharp shoulder, elbow, or chest pain.',
  },
  {
    exerciseId: 'one-arm-dumbbell-row', title: 'Supported one-arm dumbbell row', imageSrc: '/exercises/one-arm-dumbbell-row-guide.webp', imageAlt: 'Supported one-arm dumbbell row shown with the working arm long and pulled beside the torso.', muscleImageSrc: '/exercises/one-arm-dumbbell-row-muscles.webp', muscleImageAlt: 'Rear-side anatomical one-arm row illustrations showing lats and middle back in green with biceps, rear shoulder, forearm, and core in amber.',
    setup: ['Support one hand and same-side knee on a stable bench.', 'Plant the opposite foot and keep hips level.', 'Let one dumbbell hang with a neutral wrist.'], movement: ['Pull the elbow beside the torso without twisting.', 'Pause while the shoulder stays away from the ear.', 'Lower until the arm is long without dropping the shoulder.'], mistakes: ['Rotating the torso to lift the weight', 'Shrugging or pulling beyond the controlled range', 'Using momentum or an unstable bench'], selfChecks: ['From behind, the hips and shoulders remain level.', 'From the side, the elbow finishes beside the torso.', 'Three support points remain stable.'], tempo: 'Pull for 1–2 seconds, pause, and lower for about 3 seconds.', breathing: 'Exhale while pulling and inhale through the return.', primaryMuscles: ['Lats', 'middle back'], secondaryMuscles: ['Biceps', 'rear deltoids', 'forearms', 'core'], safetyNote: 'Use a stable bench and manageable load; stop for sharp shoulder, elbow, or back pain.',
  },
  {
    exerciseId: 'band-chest-press', title: 'Resistance-band chest press', imageSrc: '/exercises/band-chest-press-guide.webp', imageAlt: 'Standing band chest press shown with elbows bent and arms pressed forward from a stable rear anchor.', muscleImageSrc: '/exercises/band-chest-press-muscles.webp', muscleImageAlt: 'Front anatomical band chest press illustrations showing chest in green with triceps, front shoulders, serratus, and core in amber.',
    setup: ['Secure an intact band behind you at chest height.', 'Take a stable staggered stance with one end in each hand.', 'Start wrists over elbows and ribs stacked.'], movement: ['Press both hands forward without leaning.', 'Finish with arms long but elbows softly unlocked.', 'Return slowly until elbows reach the controlled start.'], mistakes: ['Using an unsafe anchor', 'Arching or rotating the torso', 'Letting the band snap the hands backward'], selfChecks: ['From the side, the torso remains stacked.', 'From the front, both hands travel evenly.', 'The anchor and stance stay fixed.'], tempo: 'Press for 1–2 seconds and return for about 3 seconds.', breathing: 'Exhale through the press and inhale during the return.', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'front deltoids', 'serratus anterior', 'core'], safetyNote: 'Inspect the band and anchor before use; stop for sharp shoulder, elbow, chest, or back pain.',
  },
  {
    exerciseId: 'band-row', title: 'Seated resistance-band row', imageSrc: '/exercises/band-row-guide.webp', imageAlt: 'Seated band row shown with arms long and elbows pulled beside the torso while the band stays looped around both feet.', muscleImageSrc: '/exercises/band-row-muscles.webp', muscleImageAlt: 'Rear anatomical band row illustrations showing lats and middle back in green with biceps, rear shoulders, forearms, and core in amber.',
    setup: ['Sit tall with legs extended and knees softly bent.', 'Loop an intact band securely around both mid-feet.', 'Hold equal lengths with arms long and shoulders controlled.'], movement: ['Pull elbows beside the torso without leaning back.', 'Pause as shoulder blades move back without shrugging.', 'Return slowly until the arms are long.'], mistakes: ['Looping the band near the toes', 'Rocking the torso to create momentum', 'Shrugging or snapping the band forward'], selfChecks: ['From the side, the torso angle remains steady.', 'Both band paths stay even.', 'The loop remains centered around both feet.'], tempo: 'Pull for 2 seconds, pause, and return for about 3 seconds.', breathing: 'Exhale while pulling and inhale during the return.', primaryMuscles: ['Lats', 'middle back'], secondaryMuscles: ['Biceps', 'rear deltoids', 'forearms', 'core'], safetyNote: 'Inspect the band and keep it around the mid-feet; stop for sharp shoulder, elbow, or back pain.',
  },
  {
    exerciseId: 'band-overhead-press', title: 'Resistance-band overhead press', imageSrc: '/exercises/band-overhead-press-guide.webp', imageAlt: 'Standing band overhead press shown with hands at shoulder level and arms extended overhead.', muscleImageSrc: '/exercises/band-overhead-press-muscles.webp', muscleImageAlt: 'Front anatomical band overhead press illustrations showing deltoids in green with triceps, upper chest, and core in amber.',
    setup: ['Stand evenly on the center of an intact band.', 'Hold equal ends at shoulder level with wrists neutral.', 'Stack ribs over pelvis and brace.'], movement: ['Press overhead without leaning back.', 'Finish with hands above shoulders and elbows softly unlocked.', 'Lower slowly to shoulder level.'], mistakes: ['Using uneven band lengths', 'Arching the back or flaring ribs', 'Letting the band pull the hands down quickly'], selfChecks: ['From the front, both hands finish at equal height.', 'From the side, hands stack above shoulders.', 'Feet and torso remain still.'], tempo: 'Press for 1–2 seconds and lower for about 3 seconds.', breathing: 'Brace, exhale through the press, and inhale while lowering.', primaryMuscles: ['Deltoids'], secondaryMuscles: ['Triceps', 'upper chest', 'core'], safetyNote: 'Inspect and secure the band under both feet; stop for sharp shoulder, neck, elbow, or back pain.',
  },
  {
    exerciseId: 'band-lateral-raise', title: 'Resistance-band lateral raise', imageSrc: '/exercises/band-lateral-raise-guide.webp', imageAlt: 'Band lateral raise shown with hands beside the thighs and arms raised under control to shoulder height.', muscleImageSrc: '/exercises/band-lateral-raise-muscles.webp', muscleImageAlt: 'Front anatomical band lateral raise illustrations showing middle deltoids in green with front shoulders, supraspinatus, upper trapezius, and core in amber.',
    setup: ['Stand on the center of an intact band.', 'Hold equal ends beside the thighs with wrists neutral.', 'Keep elbows softly bent and arms slightly forward.'], movement: ['Lead with elbows and raise without swinging.', 'Stop at comfortable shoulder height or earlier.', 'Lower slowly against band tension.'], mistakes: ['Shrugging toward the ears', 'Leaning or swinging for momentum', 'Raising beyond the controlled range'], selfChecks: ['From the front, both elbows rise evenly.', 'From the side, arms stay slightly forward.', 'The torso remains still.'], tempo: 'Raise for 2 seconds, pause, and lower for about 3 seconds.', breathing: 'Exhale during the raise and inhale while lowering.', primaryMuscles: ['Middle deltoids'], secondaryMuscles: ['Front deltoids', 'supraspinatus', 'upper trapezius', 'core'], safetyNote: 'Use light intact band tension and stop for sharp shoulder, neck, or elbow pain.',
  },
  {
    exerciseId: 'pike-push-up', title: 'Pike push-up', imageSrc: '/exercises/pike-push-up-guide.webp', imageAlt: 'Pike push-up shown in an inverted V and with the head lowered under control between and slightly ahead of the hands.', muscleImageSrc: '/exercises/pike-push-up-muscles.webp', muscleImageAlt: 'Side anatomical pike push-up illustrations showing shoulders and triceps in green with upper chest, serratus, and core in amber.',
    setup: ['Place hands shoulder-width and lift hips into an inverted V.', 'Keep heels raised as needed and head between the arms.', 'Set shoulders away from ears before bending elbows.'], movement: ['Bend elbows diagonally back as the head travels toward the floor.', 'Stop before shoulder control or head clearance changes.', 'Press the floor away and return to long arms.'], mistakes: ['Turning the movement into a flat push-up', 'Flaring elbows straight sideways', 'Dropping the head or forcing depth'], selfChecks: ['From the side, hips stay high throughout.', 'The head path finishes between and slightly ahead of the hands.', 'Both elbows bend evenly.'], tempo: 'Lower for about 3 seconds, pause softly, and press in 1–2 seconds.', breathing: 'Inhale during the descent and exhale through the press.', primaryMuscles: ['Deltoids', 'triceps'], secondaryMuscles: ['Upper chest', 'serratus anterior', 'core'], safetyNote: 'Use an elevated surface to reduce load and stop for sharp wrist, shoulder, neck, or elbow pain.',
  },
  {
    exerciseId: 'reverse-snow-angel', title: 'Reverse snow angel', imageSrc: '/exercises/reverse-snow-angel-guide.webp', imageAlt: 'Prone reverse snow angel shown with arms beside the hips and swept in a controlled arc toward an overhead Y.', muscleImageSrc: '/exercises/reverse-snow-angel-muscles.webp', muscleImageAlt: 'Rear anatomical reverse snow angel illustrations showing lower and middle trapezius and rear shoulders in green with rhomboids, rotator cuff, and spinal stabilizers in amber.',
    setup: ['Lie face-down with legs long and forehead hovering just above the mat.', 'Start arms beside the hips with palms down.', 'Keep ribs and pelvis in contact with the mat.'], movement: ['Sweep straight arms outward and overhead in a wide arc.', 'Reach only as far as shoulders stay away from ears.', 'Reverse the same path slowly to the hips.'], mistakes: ['Lifting the chest or arching the back', 'Shrugging or bending elbows', 'Rushing past a comfortable shoulder range'], selfChecks: ['From above, both hands trace matching arcs.', 'From the side, the chest stays close to the mat.', 'The finish forms a controlled overhead Y.'], tempo: 'Sweep for about 3 seconds each direction without resting.', breathing: 'Exhale during the overhead sweep and inhale while returning.', primaryMuscles: ['Lower trapezius', 'middle trapezius', 'rear deltoids'], secondaryMuscles: ['Rhomboids', 'rotator cuff', 'spinal stabilizers'], safetyNote: 'Use a pain-free range and stop for sharp shoulder, neck, or back pain.',
  },
  {
    exerciseId: 'shoulder-tap', title: 'Plank shoulder tap', imageSrc: '/exercises/shoulder-tap-guide.webp', imageAlt: 'High-plank shoulder tap shown with both hands down and one hand touching the opposite shoulder while the hips remain square.', muscleImageSrc: '/exercises/shoulder-tap-muscles.webp', muscleImageAlt: 'Front-side anatomical shoulder tap illustrations showing core and serratus in green with shoulders, triceps, and glute stabilizers in amber.',
    setup: ['Begin in a high plank with hands below shoulders.', 'Set feet wider than hips for a stable base.', 'Brace a straight head-to-heel body line.'], movement: ['Shift pressure minimally into one hand.', 'Tap the opposite shoulder without rotating the hips.', 'Replace the hand quietly and alternate sides.'], mistakes: ['Rocking or opening the hips', 'Rushing the taps', 'Sagging the back or shrugging the support shoulder'], selfChecks: ['From the front, hips remain level.', 'From the side, the head-to-heel line stays unchanged.', 'Each hand returns beneath its shoulder.'], tempo: 'Lift, tap, and replace each hand over about 2 seconds.', breathing: 'Breathe continuously and exhale gently during each tap.', primaryMuscles: ['Core', 'serratus anterior'], secondaryMuscles: ['Shoulders', 'triceps', 'glute stabilizers'], safetyNote: 'Widen the feet or elevate the hands for control; stop for sharp wrist, shoulder, or back pain.',
  },
  {
    exerciseId: 'mobility-flow', title: 'Hip and thoracic mobility flow', imageSrc: '/exercises/mobility-flow-guide.webp', imageAlt: 'Mobility flow showing a controlled half-kneeling hip-flexor reach and quadruped thoracic rotation.', muscleImageSrc: '/exercises/mobility-flow-muscles.webp', muscleImageAlt: 'Sports anatomy mobility illustrations showing hip flexors and thoracic rotators in green with glutes, obliques, adductors, and shoulder stabilizers in amber.',
    setup: ['Use a padded mat and begin with a half-kneeling stance.', 'Keep the pelvis gently tucked for the hip reach.', 'For rotation, place hands and knees beneath shoulders and hips.'], movement: ['Reach overhead in half kneeling without arching the back.', 'Move to all fours and place one hand behind the head.', 'Rotate the elbow upward only through a comfortable thoracic range, then switch sides.'], mistakes: ['Forcing range or holding the breath', 'Arching the lower back during the hip reach', 'Shifting the hips during thoracic rotation'], selfChecks: ['From the side, the half-kneeling ribs remain stacked.', 'In quadruped, hips stay over the knees.', 'Both sides use a smooth pain-free range.'], tempo: 'Move slowly for 3–4 breaths in each position without bouncing.', breathing: 'Inhale to prepare and exhale gently as you move into each range.', primaryMuscles: ['Hip flexors', 'thoracic rotators'], secondaryMuscles: ['Glutes', 'obliques', 'adductors', 'shoulder stabilizers'], safetyNote: 'Use comfortable range and support; stop for sharp hip, knee, shoulder, or back pain.',
  },
  {
    exerciseId: 'zone-2-treadmill', title: 'Zone 2 treadmill walk', imageSrc: '/exercises/zone-2-treadmill-guide.webp', imageAlt: 'Treadmill walking shown at an easy warm-up and a sustainable brisk incline effort with hands free.', muscleImageSrc: '/exercises/zone-2-treadmill-muscles.webp', muscleImageAlt: 'Rear-side treadmill anatomy illustrations showing cardiorespiratory system, glutes, and calves in green with quadriceps, hamstrings, and core in amber.',
    setup: ['Start the treadmill slowly before stepping into pace.', 'Stand tall with gaze forward and hands free.', 'Use an incline and speed that allow conversational breathing.'], movement: ['Build gradually from easy walking to a steady sustainable effort.', 'Use a natural heel-to-toe stride and relaxed arm swing.', 'Reduce speed before ending and step off only after the belt stops.'], mistakes: ['Holding the rails while maintaining excessive speed or incline', 'Chasing a heart-rate number despite symptoms', 'Stopping the moving belt abruptly'], selfChecks: ['From the side, posture stays upright.', 'You can speak a short sentence without gasping.', 'Stride remains smooth and repeatable.'], tempo: 'Maintain a steady conversational effort after a gradual warm-up.', breathing: 'Breathe rhythmically; reduce effort if breathing becomes strained.', primaryMuscles: ['Cardiorespiratory system', 'glutes', 'calves'], secondaryMuscles: ['Quadriceps', 'hamstrings', 'core'], safetyNote: 'Use the safety clip and stop for chest pain, dizziness, unusual breathlessness, or unstable gait.',
  },
  {
    exerciseId: 'zone-2-walk', title: 'Zone 2 walk', imageSrc: '/exercises/zone-2-walk-guide.webp', imageAlt: 'Walking shown at an easy start and a purposeful sustainable pace with natural posture and arm swing.', muscleImageSrc: '/exercises/zone-2-walk-muscles.webp', muscleImageAlt: 'Rear-side walking anatomy illustrations showing cardiorespiratory system, glutes, and calves in green with quadriceps, hamstrings, and core in amber.',
    setup: ['Choose a safe level route and supportive footwear.', 'Begin at an easy pace with tall relaxed posture.', 'Use perceived effort and conversational breathing rather than speed alone.'], movement: ['Build gradually to a purposeful sustainable walk.', 'Let the arms swing naturally with a comfortable stride.', 'Cool down at an easy pace before stopping.'], mistakes: ['Starting too fast to sustain conversation', 'Overstriding or tensing the shoulders', 'Ignoring uneven surfaces or warning symptoms'], selfChecks: ['From the side, posture remains tall and relaxed.', 'You can speak a short sentence without gasping.', 'Footfalls remain quiet and consistent.'], tempo: 'Maintain a steady conversational effort after warming up.', breathing: 'Breathe rhythmically and slow down if breathing becomes strained.', primaryMuscles: ['Cardiorespiratory system', 'glutes', 'calves'], secondaryMuscles: ['Quadriceps', 'hamstrings', 'core'], safetyNote: 'Choose a safe route and stop for chest pain, dizziness, unusual breathlessness, or unstable gait.',
  },
];

export function exerciseGuide(exerciseId: string): ExerciseGuide | undefined {
  return guides.find((guide) => guide.exerciseId === exerciseId);
}

export function exerciseGuideIds(): string[] {
  return guides.map((guide) => guide.exerciseId);
}

export function exerciseGuides(): ExerciseGuide[] {
  return guides.map((guide) => ({
    ...guide,
    setup: [...guide.setup],
    movement: [...guide.movement],
    mistakes: [...guide.mistakes],
    selfChecks: [...guide.selfChecks],
    primaryMuscles: [...guide.primaryMuscles],
    secondaryMuscles: [...guide.secondaryMuscles],
  }));
}
